---

plugins:
  - react

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es2020: true
  browser: true

extends:
  - 'airbnb'
  - 'airbnb/hooks'
  # - 'plugin:react/recommended'

parser: 'babel-eslint'

parserOptions:
  ecmaVersion: 11
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  import/resolver:
    webpack:
      config: 'config/webpack/environment.js'


rules:
  max-len: ["error", { "code": 120 }]
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
