---

version: '3'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: "make ci-check"
    depends_on:
      - postgres

    depends_on:
      - postgres

volumes:
  pgdata:
